export const GET_CITIES = "getCities"
export const GET_EVENTS = "getEvents"
export const GET_LOADING_CITIES = "getLoadingCities"
export const GET_LOADING_EVENTS = "getLoadingEvents"
export const GET_ERROR = "getError"
